name: Linter

on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  build:
    env:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_SECRET }}
      DOCKER_HUB_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    runs-on: ubuntu-latest

    container:
      image: golang:1.15.8-buster

    steps:
#      - name: Extract tag name
#        id: tag
#        uses: actions/github-script@0.2.0
#        with:
#          script: |
#            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker login --username $DOCKER_HUB_NAME --password $DOCKER_HUB_TOKEN
          docker build -t greenmailweb/kafka-ui:2.0
          docker push greenmailweb/kafka-ui:2.0
