name: Linter

on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  build:
    env:
      REPO_NAME: ${{ github.event.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Get rpositoryName
        id: name
        run: echo $REPO_NAME
#       - name: Get latest release version number
#         id: get_version
#         uses: battila7/get-version-action@v2

#       - name: Echo Tag
#         run: echo ${{ steps.get_version.outputs.version }}

#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}

#       - name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: greenmailweb/kafka-ui:${{ steps.get_version.outputs.version }}

#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}
