name: Linter

on:
  push:
    tags:
      - v*
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          script: |
            return '2.1'
#            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Echo Tag
        run: echo ${{ steps.tag.outputs.result }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: greenmailweb/kafka-ui:2.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
